server:
  port: 8081

spring:
  application:
    name: bajaj-health-challenge

# Application specific configuration
bajaj:
  webhook:
    base-url: https://bfhldevapigw.healthrx.co.in/hiring
    generate-path: /generateWebhook/JAVA
    test-path: /testWebhook/JAVA
  user:
    name: Swayam Satyameshram
    reg-no: 112215181
    email: 112215181@cse.iiitp.ac.in

logging:
  level:
    com.bajaj.finserv: DEBUG

    org.springframework.web.reactive: DEBUG
